In [127]:
import pandas as pd
import numpy as np

In [83]:
df = pd.read_csv('Titanic-Dataset.csv')

In [134]:
len(df['Age'])

891

In [142]:
Ncol = [i for i in df.columns]
Dcol = []
Nullcol = []
for i in df.columns:
    datatype = str(df[i].dtype)
    count = ((int(df[i].isnull().sum()))/len(df[i]))*100
    Dcol.append(datatype)
    Nullcol.append(count)

# Assuming you have successfully run the loop to generate Ncol, Dcol, and Nullcol

data_dict = {
    'Column Name': Ncol,
    'Data Type': Dcol,
    'Missing (%)': Nullcol
}

inspectreport = pd.DataFrame(data_dict)
with open('inspect_report' , 'w') as f:
    f.write(str(data_dict))
inspectreport

    Column Name Data Type  Missing (%)
0   PassengerId     int64     0.000000
1      Survived     int64     0.000000
2        Pclass     int64     0.000000
3          Name    object     0.000000
4           Sex    object     0.000000
5           Age   float64    19.865320
6         SibSp     int64     0.000000
7         Parch     int64     0.000000
8        Ticket    object     0.000000
9          Fare   float64     0.000000
10        Cabin    object    77.104377
11     Embarked    object     0.224467

In [63]:
df['Age'] = df['Age'].fillna(df.groupby(['Pclass', 'Sex'])['Age'].transform('median'))

In [64]:
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])

In [65]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     891 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [67]:
df.drop(labels='Cabin' , axis=1 , inplace=True)

In [68]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Embarked     891 non-null    object
dtypes: float64(2), int64(5), object(4)
memory usage: 76.7+ KB

In [69]:
df['FamilySize'] = df['SibSp'] + df['Parch']

In [70]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,FamilySize
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S,0

In [71]:
df['IsAlone'] = (df['FamilySize'] == 0).astype(int)

In [72]:
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,FamilySize,IsAlone
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S,1,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,1,0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S,0,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S,1,0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S,0,1
5,6,0,3,"Moran, Mr. James",male,25.0,0,0,330877,8.4583,Q,0,1
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,S,0,1
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,S,4,0
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,S,2,0
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,C,1,0

In [74]:
df['Age'] = df['Age'].astype('int64')

In [78]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    int64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Embarked     891 non-null    object
 11  FamilySize   891 non-null    int64
 12  IsAlone      891 non-null    int64
dtypes: float64(1), int64(8), object(4)
memory usage: 90.6+ KB

In [80]:
df.to_csv('titanic_cleaned.csv', index=False, encoding='utf-8')