In [1]:
import pandas as pd

In [3]:
df1 = pd.read_csv('titanic_cleaned.csv')
df2 = pd.read_csv('ticket_fares.csv')

In [4]:
df1.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,FamilySize,IsAlone
0,1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.2500,S,1,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,C,1,0
2,3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.9250,S,0,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1000,S,1,0
4,5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.0500,S,0,1

In [5]:
df2.head()

             Ticket     Fare
0         A/5 21171   7.2500
1          PC 17599  71.2833
2  STON/O2. 3101282   7.9250
3            113803  53.1000
4            373450   8.0500

In [ ]:
Merg_dataframe=df1.merge(df2,left_on='Ticket' , right_on='Ticket')
Merg_dataframe

In [13]:
Merg_dataframe['AgeGroup'] =  pd.cut(Merg_dataframe['Age'], bins = [0,12,19,59,200] , labels=['Child', 'Teen', 'Adult' , 'Senior'])

In [14]:
Merg_dataframe

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare_x,Embarked,FamilySize,IsAlone,Fare_y,AgeGroup
0,1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.2500,S,1,0,7.2500,Adult
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,C,1,0,71.2833,Adult
2,3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.9250,S,0,1,7.9250,Adult
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1000,S,1,0,53.1000,Adult
4,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1000,S,1,0,53.1000,Adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1588,888,1,1,"Graham, Miss. Margaret Edith",female,19,0,0,112053,30.0000,S,0,1,30.0000,Teen
1589,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,21,1,2,W./C. 6607,23.4500,S,3,0,23.4500,Adult
1590,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,21,1,2,W./C. 6607,23.4500,S,3,0,23.4500,Adult
1591,890,1,1,"Behr, Mr. Karl Howell",male,26,0,0,111369,30.0000,C,0,1,30.0000,Adult
1592,891,0,3,"Dooley, Mr. Patrick",male,32,0,0,370376,7.7500,Q,0,1,7.7500,Adult

In [16]:
Merg_dataframe.groupby(['Sex' , 'AgeGroup'])['Survived'].mean()

C:\Users\Sibghatullah\AppData\Local\Temp\ipykernel_6120\3127482570.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  Merg_dataframe.groupby(['Sex' , 'AgeGroup'])['Survived'].mean()

Sex     AgeGroup
female  Child       0.388350
        Teen        0.753247
        Adult       0.699561
        Senior      1.000000
male    Child       0.320000
        Teen        0.086957
        Adult       0.202624
        Senior      0.111111
Name: Survived, dtype: float64

In [31]:
with open('report.txt', 'w') as f:
    f.write('Women show a significantly higher survival rate than men, indicating that gender played a major role in rescue priority.\nChildren also have a noticeably better chance of survival compared to adult men, though their advantage is smaller than that of women.\nWhile not every female or child survived—and some adult men in higher classes did—the numbers clearly lean toward preferential treatment for women and younger passengers during evacuation.')

In [22]:
#Test Hypothesis 2
Merg_dataframe.groupby('Pclass')['Survived'].mean()

Pclass
1    0.689055
2    0.480000
3    0.239057
Name: Survived, dtype: float64

In [24]:
Merg_dataframe['FareBin'] = pd.qcut(Merg_dataframe['Fare_x'] , 4 , labels=['Low', 'Medium' , 'High', 'VeryHigh'])

In [25]:
Merg_dataframe

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare_x,Embarked,FamilySize,IsAlone,Fare_y,AgeGroup,FareBin
0,1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.2500,S,1,0,7.2500,Adult,Low
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,C,1,0,71.2833,Adult,VeryHigh
2,3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.9250,S,0,1,7.9250,Adult,Low
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1000,S,1,0,53.1000,Adult,High
4,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1000,S,1,0,53.1000,Adult,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1588,888,1,1,"Graham, Miss. Margaret Edith",female,19,0,0,112053,30.0000,S,0,1,30.0000,Teen,High
1589,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,21,1,2,W./C. 6607,23.4500,S,3,0,23.4500,Adult,Medium
1590,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,21,1,2,W./C. 6607,23.4500,S,3,0,23.4500,Adult,Medium
1591,890,1,1,"Behr, Mr. Karl Howell",male,26,0,0,111369,30.0000,C,0,1,30.0000,Adult,High
1592,891,0,3,"Dooley, Mr. Patrick",male,32,0,0,370376,7.7500,Q,0,1,7.7500,Adult,Low

In [26]:
Merg_dataframe.groupby('FareBin')['Survived'].mean()

C:\Users\Sibghatullah\AppData\Local\Temp\ipykernel_6120\883215743.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  Merg_dataframe.groupby('FareBin')['Survived'].mean()

FareBin
Low         0.229426
Medium      0.441687
High        0.336449
VeryHigh    0.609418
Name: Survived, dtype: float64

In [32]:
with open('report.txt' , 'a') as f:
    f.write('\n \nThe data strongly supports the “wealth” hypothesis.\nBoth Method A and Method B show that passengers in higher classes or higher fare groups had better survival rates.\nEven though the methods group the data differently, they lead to the same conclusion: wealth increased the chances of survival.')